warn_str = """# ------------------------------------------
#
# THIS MAKE FILE GENERATED BY make_make.py
#
# ------------------------------------------
"""

main_make_filename = "makefile"
front_make_debug_filename = "make_front_debug"
front_make_release_filename = "make_front_release"
# mid_make_filename = "make_mid"
# back_make_filename = "make_back"

# ------------------------------------------------------------------------------

import main_make_make

main_make_file = open(main_make_filename, "w")
main_make_file.write(warn_str + main_make_make.main_make_str)

# ------------------------------------------------------------------------------

import front_make_make

front_make_debug_file = open(front_make_debug_filename, "w")
front_make_debug_file.write(warn_str + front_make_make.front_make_debug_str)

front_make_release_file = open(front_make_release_filename, "w")
front_make_release_file.write(warn_str + front_make_make.front_make_release_str)
